---
name: Darker-Ruff Lint

on:
  pull_request:
    branches:
      - current

permissions:
  pull-requests: write
  contents: read

jobs:
  darker-ruff-lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout reusable actions repo
        uses: actions/checkout@v3
        with:
          repository: vyos/.github
          path: reusable-actions
          ref: current

      - name: Checkout head
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          path: repo

      - name: Fetch base
        run: |
          cd repo
          git fetch https://github.com/${{ github.event.pull_request.base.repo.full_name }} ${{ github.event.pull_request.base.ref }}:refs/remotes/origin/base

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install darker ruff 
        run: |
          pip install git+https://github.com/akaihola/darker.git@master ruff>=0.0.292

      - name: Analyze Code
        run: |
          cd repo
          git checkout origin/base -- ruff.toml
          cat ruff.toml
          darker -r origin/base --check --diff --lint "ruff check" --color .